function obj_data = run_leaf_generation_parallel(qsm_data, leaf_params)
%% Parallel Leaf Generation with In-Memory Processing
% This function accepts QSM data and parameters from Python and returns OBJ data
% without writing to disk, optimized for parallel processing

% Clear workspace variables but preserve inputs
clear QSM Leaves QSMbc TargetDistributions LeafProperties totalLeafArea precision

% Add the current directory and all the subdirectories to search path
addpath(genpath(pwd))

%% Initialize QSM from passed data

% QSM data is passed directly from Python
QSM = qsm_data;

%% Initialize leaf base geometry

% Vertices of the leaf base geometry
LeafProperties.vertices = [0.0    0.0    0.0;
  -0.04  0.02   0.0;
  0.0    0.10   0.0;
  0.04   0.02   0.0];

% Triangles of the leaf base geometry
LeafProperties.triangles = [1 2 3;
  1 3 4];

%% Define petiole length sampling interval

LeafProperties.petioleLengthLimits = [0.08 0.10];

%% Define target leaf distributions using parameters from Python

% LADD relative height - using parameters from Python
TargetDistributions.dTypeLADDh = 'beta';
if isfield(leaf_params, 'pLADDh')
    % Convert cell array to numeric array if needed and ensure double type
    if iscell(leaf_params.pLADDh)
        pLADDh_array = double(cell2mat(leaf_params.pLADDh));
    else
        pLADDh_array = double(leaf_params.pLADDh);
    end
    fprintf('pLADDh: %f %f\n', pLADDh_array(1), pLADDh_array(2));
    TargetDistributions.pLADDh = pLADDh_array;
else
    TargetDistributions.pLADDh = [8 3];  % Default: Moderate top concentration
end

% LADD relative branch distance - using parameters from Python
TargetDistributions.dTypeLADDd = 'weibull';
if isfield(leaf_params, 'pLADDd')
    % Convert cell array to numeric array if needed and ensure double type
    if iscell(leaf_params.pLADDd)
        pLADDd_array = double(cell2mat(leaf_params.pLADDd));
    else
        pLADDd_array = double(leaf_params.pLADDd);
    end
    fprintf('pLADDd: %f %f\n', pLADDd_array(1), pLADDd_array(2));
    TargetDistributions.pLADDd = pLADDd_array;
else
    TargetDistributions.pLADDd = [2.0 1.5];  % Default: Concentrated on outside
end

% LADD compass direction
TargetDistributions.dTypeLADDc = 'vonmises';
TargetDistributions.pLADDc = [5/4*pi 0.1];

% LOD inclination angle
TargetDistributions.dTypeLODinc = 'dewit';
TargetDistributions.fun_pLODinc = @(h,d,c) [1 2];

% LOD azimuth angle
TargetDistributions.dTypeLODaz = 'uniform';
TargetDistributions.fun_pLODaz = @(h,d,c) [];

% LSD - using parameters from Python
TargetDistributions.dTypeLSD = 'normal';
if isfield(leaf_params, 'fun_pLSD')
    % Convert cell array to numeric array if needed and ensure double type
    if iscell(leaf_params.fun_pLSD)
        fun_pLSD_array = double(cell2mat(leaf_params.fun_pLSD));
    else
        fun_pLSD_array = double(leaf_params.fun_pLSD);
    end
    fprintf('fun_pLSD: %f %f\n', fun_pLSD_array(1), fun_pLSD_array(2));
    TargetDistributions.fun_pLSD = @(h,d,c) fun_pLSD_array;
else
    TargetDistributions.fun_pLSD = @(h,d,c) [0.008 0.00025^2];  % Default: Larger leaves
end

%% Set the target leaf area using parameter from Python

if isfield(leaf_params, 'totalLeafArea')
    % Convert to numeric if needed and ensure double type
    if iscell(leaf_params.totalLeafArea)
        totalLeafArea = double(cell2mat(leaf_params.totalLeafArea));
    else
        totalLeafArea = double(leaf_params.totalLeafArea);
    end
    fprintf('totalLeafArea: %f\n', totalLeafArea);
else
    totalLeafArea = 20;  % Default: Reduced for less foliage
end

%% Generate foliage on QSM

[Leaves,QSMbc] = generate_foliage_qsm_direct(QSM,TargetDistributions, ...
  LeafProperties,totalLeafArea);

%% Export to OBJ format in memory

% Precision parameter for export
precision = 5;

% Get leaf geometry data for OBJ export
% The LeafGen library likely doesn't have export_geometry_to_string, so we'll build the OBJ manually
try
    % Get leaf triangles/geometry from the Leaves object
    % This depends on the internal structure of the Leaves object from LeafGen
    
    % Try different ways to access leaf geometry
    if isprop(Leaves, 'triangles') || isfield(Leaves, 'triangles')
        triangles = Leaves.triangles;
        fprintf('Found %d leaf triangles\n', size(triangles, 1));
        
        obj_lines = {};
        obj_lines{end+1} = '# OBJ file generated by LeafGen Parallel';
        obj_lines{end+1} = '';
        
        % Extract unique vertices from triangles
        vertices = reshape(triangles, [], 3);
        [unique_vertices, ~, vertex_indices] = unique(vertices, 'rows');
        
        % Add vertices to OBJ
        for i = 1:size(unique_vertices, 1)
            obj_lines{end+1} = sprintf('v %.6f %.6f %.6f', unique_vertices(i,1), unique_vertices(i,2), unique_vertices(i,3));
        end
        
        obj_lines{end+1} = '';
        
        % Add faces (triangles) to OBJ
        faces = reshape(vertex_indices, [], 3);
        for i = 1:size(faces, 1)
            obj_lines{end+1} = sprintf('f %d %d %d', faces(i,1), faces(i,2), faces(i,3));
        end
        
        obj_data = strjoin(obj_lines, sprintf('\n'));
        fprintf('Generated leaf OBJ data with %d characters from triangles\n', length(obj_data));
        
    else
        % Alternative: try using the export method to a temporary string
        % Create a temporary file path
        temp_dir = tempdir;
        temp_filename = fullfile(temp_dir, ['temp_leaves_' num2str(randi(10000)) '.obj']);
        
        % Export to temporary file
        Leaves.export_geometry('OBJ', true, temp_filename, precision);
        
        % Read the file content
        if exist(temp_filename, 'file')
            fid = fopen(temp_filename, 'r');
            obj_data = fread(fid, '*char')';
            fclose(fid);
            
            % Clean up temporary file
            delete(temp_filename);
            
            fprintf('Generated leaf OBJ data with %d characters from temp file\n', length(obj_data));
        else
            error('Temporary OBJ file was not created');
        end
    end
    
catch ME
    fprintf('OBJ generation failed: %s\n', ME.message);
    obj_data = '';
end

if isempty(obj_data)
    error('Failed to generate OBJ data for leaves');
end

end
